@baseurl=https://localhost:8081
@authUrl=https://localhost:8443
@authToken = {{login.response.body.access_token}}

###
###
# @name login
POST {{authUrl}}/realms/winted/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=web&username=paola123&password=paola123&grant_type=password&client_secret=wEh353Lwc2yokQMcaMHXKmm49RQ8YfCy

###
client_id=web&grant_type=client_credentials&client_secret=wEh353Lwc2yokQMcaMHXKmm49RQ8YfCy
client_id=asx&username=paola123&password=paola123&grant_type=client_credentials

###
GET {{authUrl}}/realms/winted/protocol/openid-connect/userinfo
Authorization: Bearer {{authToken}}

###
GET {{baseurl}}/api/products
Authorization: Bearer {{authToken}}

###
GET {{baseurl}}/api/products/8567ceba-9fc4-5b13-8fb3-c574bc60a362
Authorization: Bearer {{authToken}}

###
GET {{baseurl}}/api/orders
Authorization: Bearer {{authToken}}

###
GET {{baseurl}}/api/orders/72c03b3a-9c4a-4bd7-87a7-9cb17ecbc554
Authorization: Bearer {{authToken}}

###

GET {{baseurl}}/api/users/info
Authorization: Bearer {{authToken}}

###

GET {{baseurl}}/v3/api-docs
Authorization: Bearer {{authToken}}

###

GET {{baseurl}}/swagger-ui/index.html
Authorization: Bearer {{authToken}}
